"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _package_details_gold from './package-details-gold.bones.json'
import _package_details_diamond from './package-details-diamond.bones.json'
import _package_details_silver from './package-details-silver.bones.json'
import _package_details_platinum from './package-details-platinum.bones.json'
import _package_details_signature from './package-details-signature.bones.json'

registerBones({
  "package-details-gold": _package_details_gold,
  "package-details-diamond": _package_details_diamond,
  "package-details-silver": _package_details_silver,
  "package-details-platinum": _package_details_platinum,
  "package-details-signature": _package_details_signature,
})
