/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminBookingsRouteImport } from './routes/_admin/bookings'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminPatientsRouteImport } from './routes/_admin/patients'
import { Route as AdminPrescriptionsRouteImport } from './routes/_admin/prescriptions'
import { Route as AdminSubscribersRouteImport } from './routes/_admin/subscribers'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as ProtectedBookingRouteImport } from './routes/_protected/booking'
import { Route as ProtectedCartRouteImport } from './routes/_protected/cart'
import { Route as ProtectedPaymentSuccessRouteImport } from './routes/_protected/payment-success'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTrpcTodoRouteImport } from './routes/demo/trpc-todo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api/payment/callback'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedBookingRoute = ProtectedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCartRoute = ProtectedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentSuccessRoute = ProtectedPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrpcTodoRoute = DemoTrpcTodoRouteImport.update({
  id: '/demo/trpc-todo',
  path: '/demo/trpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment/callback',
  path: '/api/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/patients': typeof AdminPatientsRoute
  '/prescriptions': typeof AdminPrescriptionsRoute
  '/subscribers': typeof AdminSubscribersRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/booking': typeof ProtectedBookingRoute
  '/cart': typeof ProtectedCartRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/profile': typeof ProtectedProfileRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/patients': typeof AdminPatientsRoute
  '/prescriptions': typeof AdminPrescriptionsRoute
  '/subscribers': typeof AdminSubscribersRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/booking': typeof ProtectedBookingRoute
  '/cart': typeof ProtectedCartRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/profile': typeof ProtectedProfileRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/patients': typeof AdminPatientsRoute
  '/_admin/prescriptions': typeof AdminPrescriptionsRoute
  '/_admin/subscribers': typeof AdminSubscribersRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/booking': typeof ProtectedBookingRoute
  '/_protected/cart': typeof ProtectedCartRoute
  '/_protected/payment-success': typeof ProtectedPaymentSuccessRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookings'
    | '/dashboard'
    | '/patients'
    | '/prescriptions'
    | '/subscribers'
    | '/login'
    | '/register'
    | '/booking'
    | '/cart'
    | '/payment-success'
    | '/profile'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookings'
    | '/dashboard'
    | '/patients'
    | '/prescriptions'
    | '/subscribers'
    | '/login'
    | '/register'
    | '/booking'
    | '/cart'
    | '/payment-success'
    | '/profile'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_protected'
    | '/about'
    | '/_admin/bookings'
    | '/_admin/dashboard'
    | '/_admin/patients'
    | '/_admin/prescriptions'
    | '/_admin/subscribers'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/booking'
    | '/_protected/cart'
    | '/_protected/payment-success'
    | '/_protected/profile'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/neon'
    | '/demo/posthog'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTrpcTodoRoute: typeof DemoTrpcTodoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/patients': {
      id: '/_admin/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/prescriptions': {
      id: '/_admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subscribers': {
      id: '/_admin/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/booking': {
      id: '/_protected/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof ProtectedBookingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cart': {
      id: '/_protected/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ProtectedCartRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payment-success': {
      id: '/_protected/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof ProtectedPaymentSuccessRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trpc-todo': {
      id: '/demo/trpc-todo'
      path: '/demo/trpc-todo'
      fullPath: '/demo/trpc-todo'
      preLoaderRoute: typeof DemoTrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/callback': {
      id: '/api/payment/callback'
      path: '/api/payment/callback'
      fullPath: '/api/payment/callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBookingRoute: typeof ProtectedBookingRoute
  ProtectedCartRoute: typeof ProtectedCartRoute
  ProtectedPaymentSuccessRoute: typeof ProtectedPaymentSuccessRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBookingRoute: ProtectedBookingRoute,
  ProtectedCartRoute: ProtectedCartRoute,
  ProtectedPaymentSuccessRoute: ProtectedPaymentSuccessRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTrpcTodoRoute: DemoTrpcTodoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
